language: python
python:
  - 2.7
env:
  global:
    - secure: "UCpLs9fA5Ok2A1wYz1luSQx0f58agVHkJcnYaLZdAmTed8cLCVDDlo4mBlE3Q3KXGkctgtBL06+e6uO+gNlhpYX7ex8mW5w18ydjG3huFSCeb2Tqhs4DqqOY1C7eib9q6kO4uxItSeKtC+4GkN0rpAqhA+fVD8d8QnLSWiaOE6qHGvUNnTkvupOBoIrAQRWvYDkkKuMoijY10Aotdq2W1gjQok8u8vsipxgIdLGOIrdPmgxqfuGedDvoy8lakxmGLLFUHY8VBrzwPe47ydVtt1VSvqdWj/+u0DX0s9P2kyqTfnHpjeFydPDQFoI9d0xX3CyFlOsjiA+Yxo1TKCLeqFcUkiRN6fwBs5fgyne+rZKDurf6d1vXLQ3c+SwCg0deqwRx7bqFpVocxfu4WgsMrpz7bq+FKMlCobBM3U0Ns9qE0UiH57XqLRDfOByxG90/Zl9VguKIRKAmVbQ6Hgowz8szKYPJhVu36SIOvNklJ9wJJ9RWygUYv5n88NkHwR7uQlGbeFR3mKVyVVAuwfpyKVanMhJjdfe2rZvIjEeXOUWJzKrkHXAkWJSf4wc/k8lBpYQexeTa7hZP6GJwQ66cWYsu1Tk0qbyY6Yb+ZvMvvY5ENt2vRwGyxonBVuFL6naRghctZQ2ZyS7u8U8SsWiuJCghWMdyWflbqH78Na6PWDk=" # SNAP_API_AUTH
git:
  depth: 9999999 # Building untagged builds needs enough depth to get the latest tag
install:
  - pip install .
  - pip install coveralls
script:
  - python setup.py test
after_success:
  - coveralls
deploy:
  provider: pypi
  user: ocadotechnology
  password:
    secure: "dX2M4PpyGwa1bjpJN/Wk3EORWRXuTS14ZQEQ7Ndqk/WnOZlNqD5t/WiITTdqBWoR/ScvQiGBzR/VdRLZllkGrhupoMrtkfCldaxEI3/wbbwW9CiLuwyR/V5xgVj9TA+PtXErjgAqG9KRtyaBEOaC20t13Uc6vuIc9e6aXkzhQ9hf3vVMlnABOZP3f/2R3+sJQMLylGPCz/6BAs2U+nyxGJCpfq0aJK7H2aVPUKtM1/nscuhvsrl8yU+RWYS3idgfXDuPlwqKvRL9xbEm1DC3ByCFwwzAGCPlUtzYlx6Ttrg8Jv6S1cgsjxijzV5QqU+k1JhmY3jDqqmMROFAaY3wJ6038xUbn4zlgvXgtCayiebJukSMR7tJoVrs6ao26QPsbLNZdReDzSXJR05pgB4I8gGTlIKeZE8zOS75hkv0CdMjmIsQhTeMKqQcATuN8QszYRP4uO7vG+3I7hNSK8HcqxHtNLEDq2/QKDAVBve0R5CeEvLMnSxj7UydO+HuJUgickjHuJUmLZ+7iR9i1p6G0MUpKq/n8izSponvShu0lDshrNWJ9PYuhRD4Yvnp4/FCSxdY0+u7pHJsbluGcIvaAlwoa5O01Seu2pVpox8hVTIhn9LuR0wP7Ed4Nxper7cMNgugqb8J9BybSlMjRlBYmI7FQePCdsu1ETNI9JDHAug="
  distributions: "bdist_wheel sdist"
  on:
    all_branches: true
    repo: ocadotechnology/aimmo
after_deploy:
  - "curl -u ${SNAP_API_AUTH} -X POST -H 'Accept: application/vnd.snap-ci.com.v1+json' -H 'Content-type: application/json' https://api.snap-ci.com/project/ocadotechnology/codeforlife-deploy-appengine/branch/master/trigger"
